# Generated by Django 5.2.1 on 2026-05-26 09:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "None"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("PESCATARIAN", "Pescatarian"),
                            ("GLUTEN_FREE", "Gluten-Free"),
                            ("DAIRY_FREE", "Dairy-Free"),
                            ("NUT_FREE", "Nut-Free"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PersonGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEREMONY", "Ceremony"),
                            ("RECEPTION", "Reception"),
                            ("HOTEL", "HOTEL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address Line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, default="UK", max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "invite_code",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=17, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STANDARD", "Standard"),
                            ("BRIDESMAID", "Bridesmaid"),
                            ("GROOMSMEN", "Groomsmen"),
                            ("IMMEDIATE_FAMILY", "Immediate Family"),
                            ("BRIDE_GROOM", "Bride/Groom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("invited_to_ceremony", models.BooleanField(default=False)),
                ("invited_to_reception", models.BooleanField(default=False)),
                ("children", models.IntegerField(default=0)),
                ("pets", models.IntegerField(default=0)),
                ("allowed_plus_one", models.BooleanField(default=False)),
                ("allowed_to_stay_onsite", models.BooleanField(default=False)),
                ("allowed_to_stay_in_yurt", models.BooleanField(default=False)),
                (
                    "allowed_to_stay_night_after_reception",
                    models.BooleanField(default=False),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="data.persongroup",
                    ),
                ),
            ],
            options={
                "ordering": ["firstname"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("can_come_to_ceremony", models.BooleanField(blank=True, null=True)),
                ("can_come_to_reception", models.BooleanField(blank=True, null=True)),
                ("song_suggestion", models.CharField(max_length=255)),
                (
                    "staying_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YURT", "Yurt"),
                            ("CAMPING", "Camping"),
                            ("HOTEL", "Hotel"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "staying_night_after_reception",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "morning_meal_day_after_reception",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "evening_meal_day_after_reception",
                    models.BooleanField(blank=True, null=True),
                ),
                ("day_after_reception_suggestion", models.CharField(max_length=255)),
                (
                    "dietary_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rsvp_dietary_requirements",
                        to="data.food",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest",
                        to="data.person",
                    ),
                ),
                (
                    "plus_one",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plus_one_of",
                        to="data.person",
                    ),
                ),
            ],
            options={
                "ordering": ["guest__lastname"],
            },
        ),
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("ceremony_start_time", models.TimeField()),
                ("reception_start_time", models.TimeField()),
                ("evening_only_start_time", models.TimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "bride",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bride",
                        to="data.person",
                    ),
                ),
                (
                    "ceremony_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceremony_wedding",
                        to="data.venue",
                    ),
                ),
                (
                    "groom",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groom",
                        to="data.person",
                    ),
                ),
                (
                    "reception_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_wedding",
                        to="data.venue",
                    ),
                ),
            ],
        ),
    ]
