# Generated by Django 5.2.1 on 2025-05-17 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "None"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("PESCATARIAN", "Pescatarian"),
                            ("GLUTEN_FREE", "Gluten-Free"),
                            ("DAIRY_FREE", "Dairy-Free"),
                            ("NUT_FREE", "Nut-Free"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STANDARD", "Standard"),
                            ("BRIDESMAID", "Bridesmaid"),
                            ("GROOMSMEN", "Groomsmen"),
                            ("IMMEDIATEFAMILY", "Immediate Family"),
                            ("BRIDEGROOM", "Bride/Groom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("has_rsvp", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["firstname"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address Line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, default="UK", max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "bride",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bride",
                        to="data.person",
                    ),
                ),
                (
                    "groom",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groom",
                        to="data.person",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonFood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "food",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.food",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("person", "food")},
            },
        ),
    ]
