# Generated by Django 5.2.1 on 2026-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                (
                    "answer",
                    models.TextField(
                        help_text="Markdown or plain text format for the FAQ answer."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Used to control the display order."
                    ),
                ),
            ],
            options={
                "verbose_name": "Wedding FAQ",
                "verbose_name_plural": "Wedding FAQs",
                "ordering": ["order", "id"],
            },
        ),
    ]
