# Generated by Django 5.2.1 on 2025-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="invite_code",
            field=models.CharField(null=True, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
