# Generated by Django 5.2.1 on 2026-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_weddingfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="evening_only_reception",
            field=models.BooleanField(default=False),
        ),
    ]
