# Generated by Django 5.2.1 on 2025-10-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_person_invite_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wedding",
            name="venue",
        ),
        migrations.AddField(
            model_name="venue",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CEREMONY", "Ceremony"),
                    ("RECEPTION", "Reception"),
                    ("HOTEL", "HOTEL"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="wedding",
            name="ceremony_venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceremony_wedding",
                to="data.venue",
            ),
        ),
        migrations.AddField(
            model_name="wedding",
            name="reception_venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reception_wedding",
                to="data.venue",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="priority",
            field=models.IntegerField(
                choices=[(3, "Low"), (2, "Medium"), (1, "High")], default=1
            ),
        ),
    ]
