# Generated by Django 5.2.1 on 2026-06-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_person_evening_only_reception"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsvp",
            name="guest",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guest",
                to="data.person",
            ),
        ),
    ]
