# Generated by Django 5.2.1 on 2025-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_remove_wedding_venue_venue_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
