# Generated by Django 5.2.1 on 2026-06-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_rsvp_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="wedding",
            name="is_rsvp_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="guest",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rsvp",
                to="data.person",
            ),
        ),
    ]
