# Generated by Django 5.2.1 on 2025-10-28 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_person_address_alter_person_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="has_plus_one",
            new_name="allowed_plus_one",
        ),
        migrations.RemoveField(
            model_name="person",
            name="dietary_requirements",
        ),
        migrations.RemoveField(
            model_name="person",
            name="has_rsvp_ceremony",
        ),
        migrations.RemoveField(
            model_name="person",
            name="has_rsvp_reception",
        ),
        migrations.RemoveField(
            model_name="person",
            name="plus_one_name",
        ),
        migrations.AddField(
            model_name="person",
            name="allowed_to_stay_in_yurt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="allowed_to_stay_night_after_reception",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="allowed_to_stay_onsite",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("can_come_to_ceremony", models.BooleanField(blank=True)),
                ("can_come_to_reception", models.BooleanField(blank=True)),
                (
                    "staying_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YURT", "Yurt"),
                            ("CAMPING", "Camping"),
                            ("HOTEL", "Hotel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("staying_night_after_reception", models.BooleanField(blank=True)),
                (
                    "evening_meal_day_after_reception",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELF", "Self-catered"),
                            ("MEAL", "Meal in a pub"),
                            ("BARN", "Barn provided meal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("day_after_reception_suggestion", models.CharField(max_length=255)),
                (
                    "travel_between_venues",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "Yes, interested in options"),
                            ("NO", "No thanks"),
                            ("UNSURE", "Not sure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dietary_requirements",
                    models.ManyToManyField(blank=True, to="data.food"),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest",
                        to="data.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
