# Generated by Django 5.2.1 on 2025-11-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_rename_has_plus_one_person_allowed_plus_one_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
        migrations.RemoveField(
            model_name="person",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="person",
            name="priority",
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STANDARD", "Standard"),
                    ("BRIDESMAID", "Bridesmaid"),
                    ("GROOMSMEN", "Groomsmen"),
                    ("IMMEDIATE_FAMILY", "Immediate Family"),
                    ("BRIDE_GROOM", "Bride/Groom"),
                ],
                max_length=50,
            ),
        ),
    ]
