# Generated by Django 5.2.1 on 2026-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_wedding_is_rsvp_open_alter_rsvp_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsvp",
            name="staying_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YURT", "Yurt"),
                    ("CAMPING", "Camping"),
                    ("HOTEL", "Hotel/BnB"),
                ],
                max_length=50,
            ),
        ),
    ]
