# Generated by Django 5.2.1 on 2026-06-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_rsvp_staying_preference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["lastname", "firstname"]},
        ),
        migrations.RemoveField(
            model_name="person",
            name="children",
        ),
        migrations.RemoveField(
            model_name="person",
            name="pets",
        ),
        migrations.AddField(
            model_name="person",
            name="internal_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
