# Generated by Django 5.2.1 on 2026-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_remove_person_address_remove_person_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rsvp",
            options={"ordering": ["guest__lastname"]},
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="travel_between_venues",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes, interested in options"),
                    ("NO", "No, thanks"),
                    ("UNSURE", "Not sure"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
