# Generated by Django 5.2.1 on 2026-04-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_alter_rsvp_options_alter_rsvp_travel_between_venues_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="plus_one",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plus_one_of",
                to="data.person",
            ),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="can_come_to_ceremony",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="can_come_to_reception",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="staying_night_after_reception",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
