# Generated by Django 5.2.1 on 2026-06-29 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_alter_person_options_remove_person_children_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weddingfaq",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(2026, 6, 1, 0, 0),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weddingfaq",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
