# Generated by Django 5.2.1 on 2026-06-29 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_weddingfaq_created_weddingfaq_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceptionTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("table_number", models.PositiveIntegerField()),
                ("max_guests", models.PositiveIntegerField(default=8)),
            ],
            options={
                "ordering": ["table_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="table_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table_guests",
                to="data.receptiontable",
            ),
        ),
    ]
