# Generated by Django 5.2.1 on 2026-04-29 13:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_person_phone_rsvp_plus_one_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wedding",
            old_name="start_time",
            new_name="ceremony_start_time",
        ),
        migrations.RemoveField(
            model_name="rsvp",
            name="travel_between_venues",
        ),
        migrations.AddField(
            model_name="wedding",
            name="reception_start_time",
            field=models.TimeField(default=datetime.time(14, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="food",
            name="detail",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
