# Generated by Django 5.2.1 on 2026-04-29 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_rename_start_time_wedding_ceremony_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wedding",
            name="evening_only_start_time",
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
    ]
