# Generated by Django 5.2.1 on 2026-05-01 18:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_wedding_evening_only_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="member_of_groups",
                        through="data.PersonGroup",
                        to="data.person",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="persongroup",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="persongroup",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_details",
                to="data.group",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="persongroup",
            unique_together={("person", "group")},
        ),
        migrations.RemoveField(
            model_name="persongroup",
            name="related_person",
        ),
    ]
