# Generated by Django 5.2.1 on 2026-05-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_group_alter_persongroup_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="person",
            name="relationships",
        ),
        migrations.AddField(
            model_name="person",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="data.group",
            ),
        ),
    ]
