# Generated by Django 5.2.1 on 2026-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_remove_group_members_remove_person_relationships_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonGroup",
        ),
    ]
