# Generated by Django 5.2.1 on 2026-05-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_alter_person_group_alter_persongroup_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="PersonGroup",
        ),
    ]
