# Generated by Django 5.2.1 on 2026-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0014_rename_group_to_persongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="song_suggestion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="dietary_requirements",
            field=models.ManyToManyField(blank=True, null=True, to="data.food"),
        ),
    ]
