# Generated by Django 5.2.1 on 2026-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_rsvp_song_suggestion_alter_rsvp_dietary_requirements"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personphotogroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="personphotogroup",
            name="person",
        ),
        migrations.RemoveField(
            model_name="personphotogroup",
            name="photo_group",
        ),
        migrations.RemoveField(
            model_name="person",
            name="photo_groups",
        ),
        migrations.AddField(
            model_name="rsvp",
            name="morning_meal_day_after_reception",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="dietary_requirements",
            field=models.ManyToManyField(
                blank=True, related_name="rsvp_dietary_requirements", to="data.food"
            ),
        ),
        migrations.RemoveField(
            model_name="rsvp",
            name="evening_meal_day_after_reception",
        ),
        migrations.AddField(
            model_name="rsvp",
            name="evening_meal_day_after_reception",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PersonFood",
        ),
        migrations.DeleteModel(
            name="PersonPhotoGroup",
        ),
        migrations.DeleteModel(
            name="PhotoGroup",
        ),
    ]
